version: "3.8"

services:
  postgresdb:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER_NAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE_NAME
    ports:
      - $POSTGRES_PORT:$POSTGRES_DOCKER_PORT

  app:
    depends_on:
      - postgresdb
    build: ./
    image: machine-backend:v0.0.1
    restart: unless-stopped
    env_file: .env
    ports:
      - $APP_PORT:$APP_DOCKER_PORT
    stdin_open: true
    tty: true
